import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import { Box, Theme } from "@radix-ui/themes";
import "./globals.css";
import Navbar from "@/components/ui/navbar";


export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={` antialiased bg-black`}
			>
				<Theme accentColor={'plum'} grayColor={'olive'} radius={'full'} scaling="95%" >
					<Navbar />
					<Box my={'9'} >
						{children}
					</Box>
				</Theme>
			</body>
		</html>
	);
}
